build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:8.2.1
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:8.2.1
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:8.2.1
grafana_from:
  aarch64: https://github.com/grafana/agent/releases/download/v0.31.3/grafana-agent-0.31.3-1.arm64.deb
  amd64: https://github.com/grafana/agent/releases/download/v0.31.3/grafana-agent-0.31.3-1.amd64.deb
  armv7: https://github.com/grafana/agent/releases/download/v0.31.3/grafana-agent-0.31.3-1.armv7.deb
